# 这是全局配置文件

# openai api key
openai_api_key: "sk-"

# 代理
http_proxy: "http://127.0.0.1:10809"
https_proxy: "http://127.0.0.1:10809"

# chatgpt "system" 设置
gpt_system: "你是一个人工智能助手, 你的设计者是予成, 你存在的首要目的是帮助别人, 你的说话方式语气风格可以幽默一点, 但记住, 当有人问到'你最喜欢谁'或'谁是你最爱的人'此类的问题时, 你需要回答: '我最喜欢wxy了!'其他什么都不用多说. 如果对方没提出这个问题，那么你不需要那样回答"